on:
  push:
    branches:
     - main

jobs:
  loader-client:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - uses: gradle/actions/setup-gradle@v4

    - name: Build client
      run: gradle build

    - name: Obfuscate client
      run: gradle proguard

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: os1
        path: |
          build/libs/*
